[package]
name = "rustdtp"
version = "0.3.3"
authors = ["WKHAllen <wkhallen@gmail.com>"]
license = "MIT"
description = "Asynchronous cross-platform networking interfaces for Rust."
repository = "https://github.com/WKHAllen/rustdtp"
homepage = "https://wkhallen.com/dtp/"
keywords = ["socket", "networking"]
include = ["src/**/*", "LICENSE", "README.md"]
edition = "2021"

[dependencies]
tokio = { version = "1.26", features = ["full"] }
tokio-stream = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.5"
rsa = "0.7.2"
aes-gcm = "0.10.1"
sha2 = "0.10.6"
