[package]
name = "rustdtp"
version = "0.2.0"
authors = ["WKHAllen <wkhallen@gmail.com>"]
license = "MIT"
description = "Cross-platform networking interfaces for Rust."
repository = "https://github.com/WKHAllen/rustdtp"
keywords = ["socket", "networking"]
include = ["src/**/*", "LICENSE", "README.md"]
edition = "2021"

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
tokio-test = "0.4.2"
rand = "0.8.5"
